# Generated by Django 5.0.2 on 2024-03-02 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_date'], 'verbose_name': 'Бронювання', 'verbose_name_plural': 'Бронювання'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['room'], 'verbose_name': 'Місце', 'verbose_name_plural': 'Місця'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['category'], 'verbose_name': 'Кімната', 'verbose_name_plural': 'Кімнати'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
